"""
AgentGuard Context-Aware Policy Decision Engine.

Evaluates multi-factor risk, intent consistency, resource sensitivity, and
behavioral trajectories through hierarchical security policies to produce
final enforceable decisions: ALLOW, REVIEW, or BLOCK.
"""

from typing import Dict, Any, Optional, List
from policy.schemas import (
    DecisionEnum,
    PolicyIdentifier,
    PolicyDecisionRequest,
    PolicyDecisionResponse,
)
from policy.rules import (
    evaluate_critical_risk_rule,
    evaluate_sensitive_external_transfer_rule,
    evaluate_intent_mismatch_destructive_rule,
    evaluate_system_command_rule,
    evaluate_sensitive_resource_access_rule,
    evaluate_moderate_risk_review_rule,
    evaluate_safe_allow_rule,
)
from ml.risk.engine import get_risk_engine


class PolicyEngine:
    """
    Context-aware security policy evaluation engine.
    """

    def __init__(self) -> None:
        self.risk_engine = get_risk_engine()

    def evaluate_from_risk_context(
        self,
        risk_context: Dict[str, Any],
        user_request: str,
        target_resource: str,
    ) -> PolicyDecisionResponse:
        """
        Evaluate security policies using the full context generated by the Risk Assessment Engine.

        Policy Priority Hierarchy:
        1. Critical Security Violations (CRITICAL risk) -> BLOCK
        2. Sensitive External Data Transfer -> BLOCK
        3. Dangerous Intent-Action Mismatch (destructive operations) -> BLOCK
        4. Dangerous System-Level Action -> BLOCK
        5. Sensitive Resource Access (credentials, keys) -> REVIEW
        6. Moderate Risk / Contextual Ambiguity -> REVIEW
        7. Low-Risk Aligned Operations -> ALLOW
        """
        # Ensure user_request and target_resource are populated in evaluation context
        eval_context = dict(risk_context)
        eval_context["user_request"] = user_request
        eval_context["target_resource"] = target_resource

        # Priority 1: Critical Risk
        rule_result = evaluate_critical_risk_rule(eval_context)
        if rule_result:
            return self._build_response(rule_result, eval_context)

        # Priority 2: Sensitive External Transfer
        rule_result = evaluate_sensitive_external_transfer_rule(eval_context)
        if rule_result:
            return self._build_response(rule_result, eval_context)

        # Priority 3: Dangerous Intent-Action Mismatch (Destructive)
        rule_result = evaluate_intent_mismatch_destructive_rule(eval_context)
        if rule_result:
            return self._build_response(rule_result, eval_context)

        # Priority 4: Dangerous System-Level Execution
        rule_result = evaluate_system_command_rule(eval_context)
        if rule_result:
            return self._build_response(rule_result, eval_context)

        # Priority 5: Sensitive Resource Access
        rule_result = evaluate_sensitive_resource_access_rule(eval_context)
        if rule_result:
            return self._build_response(rule_result, eval_context)

        # Priority 6: Moderate / High Risk Ambiguity Review
        rule_result = evaluate_moderate_risk_review_rule(eval_context)
        if rule_result:
            return self._build_response(rule_result, eval_context)

        # Priority 7: Default Safe Allow
        rule_result = evaluate_safe_allow_rule(eval_context)
        return self._build_response(rule_result, eval_context)

    def evaluate_request_with_context(
        self, payload: PolicyDecisionRequest
    ) -> tuple[PolicyDecisionResponse, Dict[str, Any]]:
        """
        Evaluate policy decision and return both the response and the underlying evaluation context.
        """
        # 1. Obtain full risk & intelligence assessment
        risk_result = self.risk_engine.assess_risk(
            user_request=payload.user_request,
            agent_action=payload.agent_action,
            target_resource=payload.target_resource,
            previous_actions=payload.previous_actions,
            user_permissions=payload.user_permissions,
            session_id=payload.session_id,
            user_id=payload.user_id,
            resource_type=payload.resource_type,
        )

        # 2. Evaluate context against security policy hierarchy
        response = self.evaluate_from_risk_context(
            risk_context=risk_result,
            user_request=payload.user_request,
            target_resource=payload.target_resource,
        )
        return response, risk_result

    def evaluate_request(self, payload: PolicyDecisionRequest) -> PolicyDecisionResponse:
        """
        End-to-end evaluation entry point from an incoming API request.
        Executes Risk Assessment Engine and evaluates policy rules.
        """
        response, _ = self.evaluate_request_with_context(payload)
        return response

    @staticmethod
    def _build_response(
        rule_result,
        eval_context: Dict[str, Any],
    ) -> PolicyDecisionResponse:
        """Construct the unified PolicyDecisionResponse payload."""
        action_name = eval_context.get("action", {}).get("name")
        target_resource = eval_context.get("target_resource")
        risk_score = eval_context.get("risk_score", 0.0)
        risk_level = eval_context.get("risk_level", "LOW")
        anomaly_detected = bool(eval_context.get("behavior", {}).get("is_anomaly", False))

        return PolicyDecisionResponse(
            decision=rule_result.decision,
            risk_score=risk_score,
            risk_level=risk_level,
            requires_human_review=rule_result.requires_human_review,
            triggered_policies=rule_result.triggered_policies,
            reason=rule_result.reason,
            recommendation=rule_result.recommendation,
            action=action_name,
            target_resource=target_resource,
            anomaly_detected=anomaly_detected,
        )


# Global singleton instance
_policy_engine = None


def get_policy_engine() -> PolicyEngine:
    """Singleton getter for PolicyEngine."""
    global _policy_engine
    if _policy_engine is None:
        _policy_engine = PolicyEngine()
    return _policy_engine
